name: 🚀 Deploy website
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 📩 Get latest code
        uses: actions/checkout@v3

      - name: Run script file
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
        shell: bash

#      - name: Commit & Push changes
#        uses: actions-js/push@master
#        with:
#          github_token: ${{ secrets.GIT_TOKEN }}

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: serwer2390849.home.pl
          username: luckyswd@attract.company
          password: ${{ secrets.ftp_password }}
          local-dir: ./wp-app/
          server-dir: "./public/"
